
-- EVENTS: SPOT_ADDED (Street/Park) and DOWNHILL_ROUTE_ADDED (Downhill)
-- Generated from High Confidence CSV Data

INSERT INTO public.events (user_id, type, payload, occurred_at) VALUES 
('system', 'SPOT_ADDED', '{"spot": {"id": "assam-nfr", "name": "NFR Skatepark (Maligaon)", "type": "SKATE", "description": "Railways community skatepark (NFR). Concrete.", "location": {"lat": 26.1558, "lng": 91.6885}, "media": {"google_maps_url": "https://www.google.com/maps?q=26.1600,91.7000", "instagram_hashtags": ["#nfrskatepark", "#guwahatiskateboarding"]}, "confidence": "high", "correction_reason": "Centered on NFR Stadium complex/concrete park site."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "delhi-noida-pump", "name": "Noida Pump Track", "type": "SKATE", "description": "Pumptrack and skate areas. 100Ramps. Concrete.", "location": {"lat": 28.5794, "lng": 77.3752}, "media": {"google_maps_url": "https://www.google.com/maps?q=28.5355,77.3910", "instagram_hashtags": ["#noidapumptrack", "#noidaskateboarding"]}, "confidence": "high", "correction_reason": "Adjusted to the 100Ramps facility location in Sector 38A."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "goa-anjuna-bowl", "name": "Anjuna Bowl", "type": "SKATE", "description": "Concrete bowl & local community.", "location": {"lat": 15.5786, "lng": 73.7441}, "media": {"google_maps_url": "https://www.google.com/maps?q=15.5736,73.7406", "instagram_hashtags": ["#anjunabowl", "#goaskateboarding"]}, "confidence": "high", "correction_reason": "Pinpointed to the specific concrete bowl site near the beach path."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "goa-miramar", "name": "Miramar Skatepark", "type": "SKATE", "description": "Public skate area. Concrete.", "location": {"lat": 15.4815, "lng": 73.8052}, "media": {"google_maps_url": "https://www.google.com/maps?q=15.4732,73.8079", "instagram_hashtags": ["#miramarskatepark", "#panajiskateboarding"]}, "confidence": "high", "correction_reason": "Adjusted to the actual park concrete footprint near Miramar beach."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "gujarat-ahmedabad", "name": "Sabarmati Riverfront Skatepark", "type": "SKATE", "description": "Riverfront skate facilities. 100Ramps. Concrete.", "location": {"lat": 23.0232, "lng": 72.5694}, "media": {"google_maps_url": "https://www.google.com/maps?q=23.0225,72.5714", "instagram_hashtags": ["#sabarmatiriverfront", "#ahmedabadskateboarding"]}, "confidence": "high", "correction_reason": "Placed on the dedicated riverfront promenade plaza."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "karnataka-blr-holystoked", "name": "Holystoked Skatepark", "type": "SKATE", "description": "Community-built park. Concrete.", "location": {"lat": 13.0645, "lng": 77.5878}, "media": {"google_maps_url": "https://www.google.com/maps?q=12.9352,77.6245", "instagram_hashtags": ["#holystoked", "#bengaluruskateboarding"]}, "confidence": "high", "correction_reason": "Relocated from generic Koramangala to the site in Yelahanka."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "karnataka-blr-play", "name": "Play Arena Skatepark", "type": "SKATE", "description": "Commercial skatepark. Concrete.", "location": {"lat": 12.9038, "lng": 77.6745}, "media": {"google_maps_url": "https://www.google.com/maps?q=12.8426,77.6648", "instagram_hashtags": ["#playarena", "#bengaluruskateboarding"]}, "confidence": "high", "correction_reason": "Centered on the Play Arena commercial skatepark facility."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "mp-panna-janwaar", "name": "Janwaar Skatepark", "type": "SKATE", "description": "Rural skatepark. Concrete.", "location": {"lat": 24.3643, "lng": 80.1466}, "media": {"google_maps_url": "https://www.google.com/maps?q=24.3300,80.2700", "instagram_hashtags": ["#janwaar", "#pannaskateboarding"]}, "confidence": "high", "correction_reason": "Precise village location for the Janwaar rural skatepark."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "maharashtra-mumbai-carter", "name": "Carter Road Skatepark", "type": "SKATE", "description": "Public promenade skatepark. Concrete.", "location": {"lat": 19.0682, "lng": 72.8220}, "media": {"google_maps_url": "https://www.google.com/maps?q=19.0607,72.8227", "instagram_hashtags": ["#carterroad", "#mumbaiskateboarding"]}, "confidence": "high", "correction_reason": "Placed on the pedestrian promenade section where skating occurs."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "maharashtra-navi-mumbai-nerul", "name": "Nerul Skatepark", "type": "SKATE", "description": "Concrete plaza with modules.", "location": {"lat": 19.0270, "lng": 73.0150}, "media": {"google_maps_url": "https://www.google.com/maps?q=19.0365,73.0186", "instagram_hashtags": ["#nerulskatepark", "#navimumbaiskateboarding"]}, "confidence": "high", "correction_reason": "Adjusted to the municipal skatepark grounds in Nerul."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "rajasthan-khempur", "name": "Desert Dolphin Skatepark", "type": "SKATE", "description": "Large transition skatepark. Concrete.", "location": {"lat": 24.6366, "lng": 73.8569}, "media": {"google_maps_url": "https://www.google.com/maps?q=26.2100,73.3200", "instagram_hashtags": ["#desertdolphin", "#khempurskateboarding"]}, "confidence": "high", "correction_reason": "Corrected to the Khempur site (Udaipur region) where the park is built."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "telangana-hyderabad-wallride", "name": "WallRide Park (Peerancheru)", "type": "SKATE", "description": "Pump track + skatepark. Concrete.", "location": {"lat": 17.3486, "lng": 78.3795}, "media": {"google_maps_url": "https://www.google.com/maps?q=17.3000,78.4250", "instagram_hashtags": ["#wallridepark", "#hyderabadskateboarding"]}, "confidence": "high", "correction_reason": "Specific facility location in Peerancheru."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "andhra-rk-beach", "name": "RK Beach promenade", "type": "SKATE", "description": "Beach promenade cruising. Concrete / Tiles / Asphalt.", "location": {"lat": 17.6868, "lng": 83.2185}, "media": {"google_maps_url": "https://www.google.com/maps?q=17.6868,83.2185", "instagram_hashtags": ["#rkbeach", "#visakhapatnamskateboarding"]}, "confidence": "high", "correction_reason": "Confirmed on the pedestrian promenade tiles."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "delhi-cp-inner", "name": "Connaught Place (Inner Circle)", "type": "SKATE", "description": "Classic plaza – ledges and tiles. Concrete / Tiles / Asphalt.", "location": {"lat": 28.6328, "lng": 77.2197}, "media": {"google_maps_url": "https://www.google.com/maps?q=28.6315,77.2167", "instagram_hashtags": ["#connaughtplace", "#newdelhiskateboarding"]}, "confidence": "high", "correction_reason": "Centered on the wide pedestrian corridor of the Inner Circle."}}', NOW()),

('system', 'DOWNHILL_ROUTE_ADDED', '{"spot": {"id": "karnataka-nandi-hills", "name": "Nandi Hills", "type": "DOWNHILL", "description": "Famous downhill run. Asphalt (mountain road).", "location": {"lat": 13.3850, "lng": 77.6960}, "media": {"google_maps_url": "https://www.google.com/maps?q=13.3702,77.6835", "instagram_hashtags": ["#nandihills", "#bengalurudownhill"]}, "confidence": "high", "correction_reason": "Moved to the start of the switchback technical descent."}}', NOW()),

('system', 'DOWNHILL_ROUTE_ADDED', '{"spot": {"id": "karnataka-agumbe", "name": "Agumbe Ghat Road", "type": "DOWNHILL", "description": "Rainforest descent (technical). Asphalt (mountain road).", "location": {"lat": 13.5042, "lng": 75.0885}, "media": {"google_maps_url": "https://www.google.com/maps?q=13.5019,75.1606", "instagram_hashtags": ["#agumbeghat", "#shimogadownhill"]}, "confidence": "high", "correction_reason": "Shifted to the technical hairpin section of the descent."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "karnataka-kanteerava", "name": "Kanteerava Stadium", "type": "SKATE", "description": "Legendary street hub with granite plazas and stairs. Granite.", "location": {"lat": 12.9695, "lng": 77.5925}, "media": {"google_maps_url": "", "instagram_hashtags": ["#kanteerava", "#bengaluruskateboarding"]}, "confidence": "high", "correction_reason": "Newly identified essential spot."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "kerala-kochi-sparky", "name": "Kochi Skatepark (Sparky)", "type": "SKATE", "description": "New concrete park in Panampilly Nagar area. Concrete.", "location": {"lat": 9.9610, "lng": 76.2935}, "media": {"google_maps_url": "", "instagram_hashtags": ["#kochiskatepark", "#kochiskateboarding"]}, "confidence": "high", "correction_reason": "Newly identified essential spot."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "maharashtra-mumbai-dmonte", "name": "D’Monte Park (DIY)", "type": "SKATE", "description": "Community DIY space with flatground and obstacles. Concrete.", "location": {"lat": 19.0565, "lng": 72.8285}, "media": {"google_maps_url": "", "instagram_hashtags": ["#dmontepark", "#mumbaiskateboarding"]}, "confidence": "high", "correction_reason": "Newly identified essential spot."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "delhi-freemotion", "name": "Freemotion Sk8", "type": "SKATE", "description": "Indoor wooden park facility in Saket. Wood.", "location": {"lat": 28.5205, "lng": 77.2115}, "media": {"google_maps_url": "", "instagram_hashtags": ["#freemotionsk8", "#newdelhiskateboarding"]}, "confidence": "high", "correction_reason": "Newly identified essential spot."}}', NOW()),

('system', 'SPOT_ADDED', '{"spot": {"id": "pune-diy-cave", "name": "Pune DIY (The Cave)", "type": "SKATE", "description": "Under-bridge DIY spot near Mundhwa. Concrete.", "location": {"lat": 18.5350, "lng": 73.9180}, "media": {"google_maps_url": "", "instagram_hashtags": ["#punediy", "#puneskateboarding"]}, "confidence": "high", "correction_reason": "Newly identified essential spot."}}', NOW());
